version: '3'
services:
  app:
    restart: always
    image: lalwrj/spring-boot2-shopping:1.0-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: local
    restart: always
    ports:
    - 9090:8080

  nginx:
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
   depends_on:
    - app
   links:
    - app

networks:
  custom-driver-1:
    driver: bridge