spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    # template-resolver-order:
    # view-names:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
#    http://localhost:8080/h2-console

#logging color
spring:
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      hibernate:TRACE

# 페이스북
facebook:
  client:
     clientId: 746000202255574
     clientSecret: 1a9be60fbfc44a15324acf1ebf121ed1
     accessTokenUri: https://graph.facebook.com/oauth/access_token
     userAuthorizationUri: https://www.facebook.com/dialog/oauth
     tokenName: oauth_token
     authenticationScheme: query
     clientAuthenticationScheme: form
     scope: email
  resource:
     userInfoUri: https://graph.facebook.com/me?fields=email,name,id
logging:
  config:
  exception-conversion-word:


#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password:


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/helloboard?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: fastcamp
#    password: fastcamp

