spring:
  profiles: local
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: lo
      password: lo

#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password:


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/helloboard?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: fastcamp
#    password: fastcamp

